version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  search-ui:
    image: docker.elastic.co/enterprise-search/search-ui:latest
    container_name: search-ui
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./config/search-ui.json:/usr/share/nginx/html/config.json:ro